@url = http://localhost:3611

### ROOT
{{url}}

### BASE
POST {{url}}/login
content-type: application/json

{
	"password": "123"
}

### BASE
{{url}}

### GET LOGGED IN USER GET 
POST {{url}}/currentuser
