@url = http://localhost:3611

### ROOT
GET {{url}}

### WELCOME MESSAGE
GET {{url}}/welcomemessage

### BASE
POST {{url}}/login
content-type: application/json

{
	"password": "123"
}

### GET LOGGED IN USER GET 
GET {{url}}/currentuser

### LOGOUT
GET {{url}}/logout